version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "0.11.1"
    MODULE_PATH: "tf_security_groups/sg_ssh"

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - echo $TERRAFORM_VERSION
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.1/terraform_0.11.1_linux_amd64.zip && unzip terraform.zip
      - mv terraform /usr/local/bin
      - apt-get update
      - apt-get -y install python3 python3-pip
      - pip3 install terrascan
      - echo "Validating terraform and terrascan installs" && terraform -v && terrascan -h
  build:
    commands:
      - echo "Testing terraform format"
      - terraform fmt $MODULE_PATH
      - echo "Running terrascan"
      - terrascan -l $MODULE_PATH -t security_group
      - echo "Running tests"
      - cd $MODULE_PATH/tests
      - terraform init -input=false
      - terraform plan -out=tfplan -input=false
      - terraform apply -input=false tfplan
  post_build:
    commands:
      - terraform destroy -force
