version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "0.11.1"
    MODULE_PATH: "tf_security_groups/sg_ssh"

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - echo $TERRAFORM_VERSION
      - apt-get install curl
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.1/terraform_0.11.1_linux_amd64.zip && unzip terraform.zip
      - ls -al
      - pip --version
      - python --version
      - pip install terrascan
  pre_build:
    commands:
      - ./terraform fmt $MODULE_PATH
  build:
    commands:
      - cd $MODULE_PATH
      - ./terraform init
