version: 0.2

phases:
  install:
    commands:
      - curl -o terraform.zip ${TERRAFORM_DOWNLOAD_URL} && unzip terraform.zip
      - mv terraform /usr/local/bin
  build:
    commands:
      - terraform fmt $MODULE_PATH | tee terraform-fmt-result.txt
  post_build:
    commands:
      - if [ -s terraform-fmt-result.txt ]; then echo "Failed. Templates are not formatted. Please run 'terraform fmt'" && exit 1; else echo "Success! Templates are formatted."; fi
artifacts:
  files:
    - terraform-fmt-result.txt
  discard-paths: yes
