version: 0.2

phases:
  install:
    commands:
      - curl -o terraform.zip ${TERRAFORM_DOWNLOAD_URL} && unzip terraform.zip
      - mv terraform /usr/local/bin
  build:
    commands:
      - cd $MODULE_PATH/tests
      - terraform init -input=false -no-color
      - terraform plan -out=tfplan -input=false -no-color | tee plan.log
artifacts:
  files:
    - $MODULE_PATH/tests/plan.log
    - $MODULE_PATH/tests/tfplan
    - ci/buildspec-terraform-apply.yml
  discard-paths: yes
