version: 0.2

phases:
  install:
    commands:
      - echo $TERRAFORM_DOWNLOAD_URL
      - curl -o terraform.zip ${TERRAFORM_DOWNLOAD_URL} && unzip terraform.zip
      - mv terraform /usr/local/bin
  build:
    commands:
#      - terraform fmt $MODULE_PATH | tee terraform-fmt-result.txt
      - format_status=$(terraform fmt $MODULE_PATH | wc -l)
      - if [ $format_status -gt 0 ]; then echo "Failed. Templates are not formatted. Please run 'terraform fmt'" && exit 1; else echo "Success! Templates are formatted."; fi
#  post_build:
#    commands:
#      - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
#      # Packer doesn't return non-zero status; we must do that if Packer build failed
#      - test -s ami_id.txt || exit 1
#      - sed -i.bak "s/<<AMI-ID>>/$(cat ami_id.txt)/g" ami_builder_event.json
#      - aws events put-events --entries file://ami_builder_event.json
#      - echo "build completed on `date`"
#artifacts:
#  files:
#    - terraform-fmt-result.txt
#  discard-paths: yes
