version: 0.2

phases:
  install:
    commands:
      - curl -o terraform.zip ${TERRAFORM_DOWNLOAD_URL} && unzip terraform.zip
      - mv terraform /usr/local/bin
  build:
    commands:
      - terraform fmt $MODULE_PATH | tee terraform-fmt-result.txt
      - ! test -s terraform-fmt-result.txt || exit 1
artifacts:
  files:
    - terraform-fmt-result.txt
  discard-paths: yes
